$(document).ready(function () {
    // Use the given data to create  
    // the table and display it 
    $('table').bootstrapTable({
        data: mydata,
        search: true
    });

    $('table').on('search', function () {
        $('table').bootstrapTable('filter', $(this).val(), '=');
    });

    $('.loading').show();
});

// Specify the JSON data to be displayed 
var mydata =
    [
        // {
        //     "STT": "",
        //     "Số hóa đơn": "",
        //     "Ngày tháng, năm phát hành": "",
        //     "Tháng, năm kê khai": "",
        //     "Tên người mua": "",
        //     "Mã số thuế người mua": "",
        //     "Mặt hàng": "",
        //     "Doanh số bán chưa có thuế": "",
        //     "Thuế GTGT": "",
        //     "Tổng tiền": ""
        // },
        {
            "STT": "1",
            "Số hóa đơn": "96",
            "Ngày tháng, năm phát hành": "21/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC cáp quang truyền dẫn",
            "Doanh số bán chưa có thuế": "65.947.215",
            "Thuế GTGT": "6.594.722",
            "Tổng tiền": "72.541.937"
        },
        {
            "STT": "2",
            "Số hóa đơn": "97",
            "Ngày tháng, năm phát hành": "24/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "340.648.876",
            "Thuế GTGT": "34.064.888",
            "Tổng tiền": "374.713.764"
        },
        {
            "STT": "3",
            "Số hóa đơn": "98",
            "Ngày tháng, năm phát hành": "25/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "590.130.393",
            "Thuế GTGT": "59.013.039",
            "Tổng tiền": "649.143.432"
        },
        {
            "STT": "4",
            "Số hóa đơn": "99",
            "Ngày tháng, năm phát hành": "25/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "634.699.428",
            "Thuế GTGT": "63.469.943",
            "Tổng tiền": "698.169.371"
        },
        {
            "STT": "5",
            "Số hóa đơn": "100",
            "Ngày tháng, năm phát hành": "25/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "369.122.826",
            "Thuế GTGT": "36.912.283",
            "Tổng tiền": "406.035.109"
        },
        {
            "STT": "6",
            "Số hóa đơn": "102",
            "Ngày tháng, năm phát hành": "25/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "134.286.353",
            "Thuế GTGT": "13.428.635",
            "Tổng tiền": "147.714.988"
        },
        {
            "STT": "7",
            "Số hóa đơn": "103",
            "Ngày tháng, năm phát hành": "25/1/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "402.431.455",
            "Thuế GTGT": "40.243.145",
            "Tổng tiền": "442.674.600"
        },
        {
            "STT": "8",
            "Số hóa đơn": "104",
            "Ngày tháng, năm phát hành": "21/2/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Thu hồi cáp phục vụ ngầm hoá đường Lý Chính Thắng",
            "Doanh số bán chưa có thuế": "16.653.729",
            "Thuế GTGT": "1.665.373",
            "Tổng tiền": "18.319.102"
        },
        {
            "STT": "9",
            "Số hóa đơn": "105",
            "Ngày tháng, năm phát hành": "25/2/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Triển khai cáp quang thuê bao",
            "Doanh số bán chưa có thuế": "104.081.894",
            "Thuế GTGT": "10.408.189",
            "Tổng tiền": "114.490.083"
        },
        {
            "STT": "10",
            "Số hóa đơn": "106",
            "Ngày tháng, năm phát hành": "27/2/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC cáp quang phục vụ di dời KDC",
            "Doanh số bán chưa có thuế": "22.655.385",
            "Thuế GTGT": "2.265.539",
            "Tổng tiền": "24.920.924"
        },
        {
            "STT": "11",
            "Số hóa đơn": "107",
            "Ngày tháng, năm phát hành": "14/3/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Cải tạo nhà trạm tại TP.HCM",
            "Doanh số bán chưa có thuế": "377.207.950",
            "Thuế GTGT": "37.720.795",
            "Tổng tiền": "414.928.745"
        },
        {
            "STT": "12",
            "Số hóa đơn": "109",
            "Ngày tháng, năm phát hành": "20/3/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Thu hồi viba tại TP.HCM",
            "Doanh số bán chưa có thuế": "8.678.395",
            "Thuế GTGT": "867.84",
            "Tổng tiền": "9.546.235"
        },
        {
            "STT": "13",
            "Số hóa đơn": "110",
            "Ngày tháng, năm phát hành": "22/3/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC cáp quang truyền dẫn",
            "Doanh số bán chưa có thuế": "182.428.705",
            "Thuế GTGT": "18.242.870",
            "Tổng tiền": "200.671.575"
        },
        {
            "STT": "14",
            "Số hóa đơn": "111",
            "Ngày tháng, năm phát hành": "22/3/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "474.090.747",
            "Thuế GTGT": "47.409.075",
            "Tổng tiền": "521.499.822"
        },
        {
            "STT": "15",
            "Số hóa đơn": "112",
            "Ngày tháng, năm phát hành": "28/3/2019",
            "Tháng, năm kê khai": "Q1/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Thu hồi cáp quang phục vụ ngầm hoá Lý Chính Thắng",
            "Doanh số bán chưa có thuế": "9.854.625",
            "Thuế GTGT": "985.462",
            "Tổng tiền": "10.840.087"
        },
        {
            "STT": "16",
            "Số hóa đơn": "113",
            "Ngày tháng, năm phát hành": "20/4/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC phục vụ di dời nắn dịch",
            "Doanh số bán chưa có thuế": "58.320.404",
            "Thuế GTGT": "5.832.040",
            "Tổng tiền": "64.152.444"
        },
        {
            "STT": "17",
            "Số hóa đơn": "114",
            "Ngày tháng, năm phát hành": "20/4/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "390.807.111",
            "Thuế GTGT": "39.080.711",
            "Tổng tiền": "429.887.822"
        },
        {
            "STT": "18",
            "Số hóa đơn": "115",
            "Ngày tháng, năm phát hành": "22/4/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "824.609.459",
            "Thuế GTGT": "82.460.946",
            "Tổng tiền": "907.070.405"
        },
        {
            "STT": "19",
            "Số hóa đơn": "116",
            "Ngày tháng, năm phát hành": "23/4/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC tuyến cáp quang truyền dẫn",
            "Doanh số bán chưa có thuế": "79.805.890",
            "Thuế GTGT": "7.980.589",
            "Tổng tiền": "87.786.479"
        },
        {
            "STT": "20",
            "Số hóa đơn": "117",
            "Ngày tháng, năm phát hành": "25/4/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Bệnh Viện Đa Khoa Quốc Tế SIS Cần Thơ- CN Cty TNHH ĐT YT Việt Cường",
            "Mã số thuế người mua": "0312592908-002",
            "Mặt hàng": "Lắp đặt ống nhựa, thang máng cáp, kéo và hàn nối cáp quang",
            "Doanh số bán chưa có thuế": "920.145.000",
            "Thuế GTGT": "92.014.500",
            "Tổng tiền": "1.012.159.500"
        },
        {
            "STT": "21",
            "Số hóa đơn": "118",
            "Ngày tháng, năm phát hành": "2/5/19",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC lắp đặt hệ thống Camera",
            "Doanh số bán chưa có thuế": "175.197.000",
            "Thuế GTGT": "17.519.700",
            "Tổng tiền": "192.716.700"
        },
        {
            "STT": "22",
            "Số hóa đơn": "121",
            "Ngày tháng, năm phát hành": "13/5/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "216.007.164",
            "Thuế GTGT": "21.600.716",
            "Tổng tiền": "237.607.880"
        },
        {
            "STT": "23",
            "Số hóa đơn": "122",
            "Ngày tháng, năm phát hành": "13/5/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "375.215.100",
            "Thuế GTGT": "37.521.510",
            "Tổng tiền": "412.736.610"
        },
        {
            "STT": "24",
            "Số hóa đơn": "123",
            "Ngày tháng, năm phát hành": "18/6/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Xây dựng 10 trạm CĐBR phục vụ ngầm hoá",
            "Doanh số bán chưa có thuế": "330.512.291",
            "Thuế GTGT": "33.051.229",
            "Tổng tiền": "363.563.520"
        },
        {
            "STT": "25",
            "Số hóa đơn": "124",
            "Ngày tháng, năm phát hành": "25/6/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC 232 tuyến cáp quang",
            "Doanh số bán chưa có thuế": "25.602.002",
            "Thuế GTGT": "2.560.200",
            "Tổng tiền": "28.162.202"
        },
        {
            "STT": "26",
            "Số hóa đơn": "125",
            "Ngày tháng, năm phát hành": "25/6/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC tuyến cáp quang truyền dẫn",
            "Doanh số bán chưa có thuế": "18.034.416",
            "Thuế GTGT": "1.803.442",
            "Tổng tiền": "19.837.858"
        },
        {
            "STT": "27",
            "Số hóa đơn": "126",
            "Ngày tháng, năm phát hành": "25/6/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "31.842.309",
            "Thuế GTGT": "3.184.231",
            "Tổng tiền": "35.026.540"
        },
        {
            "STT": "28",
            "Số hóa đơn": "127",
            "Ngày tháng, năm phát hành": "25/6/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "82.498.345",
            "Thuế GTGT": "8.249.835",
            "Tổng tiền": "90.748.180"
        },
        {
            "STT": "29",
            "Số hóa đơn": "129",
            "Ngày tháng, năm phát hành": "25/6/2019",
            "Tháng, năm kê khai": "Q2/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "317.023.336",
            "Thuế GTGT": "31.702.333",
            "Tổng tiền": "348.725.669"
        },
        {
            "STT": "30",
            "Số hóa đơn": "133",
            "Ngày tháng, năm phát hành": "22/7/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Lắp đặt thiết bị viba",
            "Doanh số bán chưa có thuế": "14.672.927",
            "Thuế GTGT": "1.467.293",
            "Tổng tiền": "16.140.220"
        },
        {
            "STT": "31",
            "Số hóa đơn": "134",
            "Ngày tháng, năm phát hành": "23/7/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "514.692.131",
            "Thuế GTGT": "51.469.213",
            "Tổng tiền": "566.161.344"
        },
        {
            "STT": "32",
            "Số hóa đơn": "135",
            "Ngày tháng, năm phát hành": "24/7/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "778.690.977",
            "Thuế GTGT": "77.869.098",
            "Tổng tiền": "856.560.075"
        },
        {
            "STT": "33",
            "Số hóa đơn": "136",
            "Ngày tháng, năm phát hành": "25/7/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "361.598.901",
            "Thuế GTGT": "36.159.890",
            "Tổng tiền": "397.758.791"
        },
        {
            "STT": "34",
            "Số hóa đơn": "137",
            "Ngày tháng, năm phát hành": "29/7/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "XD mạng cáp thuê bao tại dự án khu Villa",
            "Doanh số bán chưa có thuế": "35.758.067",
            "Thuế GTGT": "3.575.807",
            "Tổng tiền": "39.333.874"
        },
        {
            "STT": "35",
            "Số hóa đơn": "139",
            "Ngày tháng, năm phát hành": "19/8/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "XD mạng cáp thuê bao tại dự án khu Villa",
            "Doanh số bán chưa có thuế": "8.933.657",
            "Thuế GTGT": "893.366",
            "Tổng tiền": "9.827.023"
        },
        {
            "STT": "36",
            "Số hóa đơn": "140",
            "Ngày tháng, năm phát hành": "20/8/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Bệnh Viện Đa Khoa Quốc Tế SIS Cần Thơ- CN Cty TNHH ĐT YT Việt Cường",
            "Mã số thuế người mua": "0312592908-002",
            "Mặt hàng": "CC vật tư và thi công hệ thống báo tự động",
            "Doanh số bán chưa có thuế": "234.398.000",
            "Thuế GTGT": "23.439.800",
            "Tổng tiền": "257.837.800"
        },
        {
            "STT": "37",
            "Số hóa đơn": "143",
            "Ngày tháng, năm phát hành": "24/8/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "300.110.480",
            "Thuế GTGT": "30.011.048",
            "Tổng tiền": "330.121.528"
        },
        {
            "STT": "38",
            "Số hóa đơn": "146",
            "Ngày tháng, năm phát hành": "27/8/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "Lắp đặt 11 tuyến viba",
            "Doanh số bán chưa có thuế": "58.671.831",
            "Thuế GTGT": "5.867.183",
            "Tổng tiền": "64.539.014"
        },
        {
            "STT": "39",
            "Số hóa đơn": "147",
            "Ngày tháng, năm phát hành": "28/9/2019",
            "Tháng, năm kê khai": "Q3/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC tuyến cáp quang truyền dẫn",
            "Doanh số bán chưa có thuế": "169.250.970",
            "Thuế GTGT": "16.925.097",
            "Tổng tiền": "186.176.067"
        },
        {
            "STT": "40",
            "Số hóa đơn": "148",
            "Ngày tháng, năm phát hành": "1/10/19",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC tuyến cáp quang phục vụ mở rộng",
            "Doanh số bán chưa có thuế": "220.807.598",
            "Thuế GTGT": "22.080.760",
            "Tổng tiền": "242.888.358"
        },
        {
            "STT": "41",
            "Số hóa đơn": "149",
            "Ngày tháng, năm phát hành": "8/10/19",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "18.685.929",
            "Thuế GTGT": "1.868.593",
            "Tổng tiền": "20.554.522"
        },
        {
            "STT": "42",
            "Số hóa đơn": "150",
            "Ngày tháng, năm phát hành": "8/10/19",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC cáp quang truyền dẫn",
            "Doanh số bán chưa có thuế": "170.998.984",
            "Thuế GTGT": "17.099.898",
            "Tổng tiền": "188.098.882"
        },
        {
            "STT": "43",
            "Số hóa đơn": "1",
            "Ngày tháng, năm phát hành": "16/10/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "488.438.436",
            "Thuế GTGT": "48.843.844",
            "Tổng tiền": "537.282.280"
        },
        {
            "STT": "44",
            "Số hóa đơn": "2",
            "Ngày tháng, năm phát hành": "21/10/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "316.088.384",
            "Thuế GTGT": "31.608.838",
            "Tổng tiền": "347.697.222"
        },
        {
            "STT": "45",
            "Số hóa đơn": "3",
            "Ngày tháng, năm phát hành": "22/10/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "XD mới hạ tầng viễn thông",
            "Doanh số bán chưa có thuế": "43.445.102",
            "Thuế GTGT": "4.344.510",
            "Tổng tiền": "47.789.612"
        },
        {
            "STT": "46",
            "Số hóa đơn": "4",
            "Ngày tháng, năm phát hành": "22/10/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "XD mới hạ tầng viễn thông",
            "Doanh số bán chưa có thuế": "62.272.050",
            "Thuế GTGT": "6.227.205",
            "Tổng tiền": "68.499.255"
        },
        {
            "STT": "47",
            "Số hóa đơn": "5",
            "Ngày tháng, năm phát hành": "22/10/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Ban Quản Trị Nhà Chung Cư Lê Thành Khu B",
            "Mã số thuế người mua": "314968257",
            "Mặt hàng": "TC lắp đặt hệ thống Camera",
            "Doanh số bán chưa có thuế": "9.000.000",
            "Thuế GTGT": "900",
            "Tổng tiền": "9.900.000"
        },
        {
            "STT": "48",
            "Số hóa đơn": "6",
            "Ngày tháng, năm phát hành": "22/10/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "651.837.391",
            "Thuế GTGT": "65.183.739",
            "Tổng tiền": "717.021.130"
        },
        {
            "STT": "49",
            "Số hóa đơn": "7",
            "Ngày tháng, năm phát hành": "28/11/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC thu hồi các tuyến cáp quang",
            "Doanh số bán chưa có thuế": "35.647.952",
            "Thuế GTGT": "3.564.795",
            "Tổng tiền": "39.212.747"
        },
        {
            "STT": "50",
            "Số hóa đơn": "8",
            "Ngày tháng, năm phát hành": "28/11/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC các tuyến cáp quang",
            "Doanh số bán chưa có thuế": "51.231.219",
            "Thuế GTGT": "5.123.122",
            "Tổng tiền": "56.354.341"
        },
        {
            "STT": "51",
            "Số hóa đơn": "9",
            "Ngày tháng, năm phát hành": "19/12/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC các tuyến cáp quang",
            "Doanh số bán chưa có thuế": "17.659.688",
            "Thuế GTGT": "1.765.969",
            "Tổng tiền": "19.425.657"
        },
        {
            "STT": "52",
            "Số hóa đơn": "10",
            "Ngày tháng, năm phát hành": "19/12/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC cải tạo cống bể",
            "Doanh số bán chưa có thuế": "21.633.988",
            "Thuế GTGT": "2.163.399",
            "Tổng tiền": "23.797.387"
        },
        {
            "STT": "53",
            "Số hóa đơn": "11",
            "Ngày tháng, năm phát hành": "23/12/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC các tuyến cáp quang",
            "Doanh số bán chưa có thuế": "135.638.376",
            "Thuế GTGT": "13.563.837",
            "Tổng tiền": "149.202.213"
        },
        {
            "STT": "54",
            "Số hóa đơn": "12",
            "Ngày tháng, năm phát hành": "23/12/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC các tuyến cáp quang ngầm",
            "Doanh số bán chưa có thuế": "30.909.091",
            "Thuế GTGT": "3.090.909",
            "Tổng tiền": "34.000.000"
        },
        {
            "STT": "55",
            "Số hóa đơn": "13",
            "Ngày tháng, năm phát hành": "24/12/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC các tuyến cáp quang",
            "Doanh số bán chưa có thuế": "191.709.151",
            "Thuế GTGT": "19.170.915",
            "Tổng tiền": "210.880.066"
        },
        {
            "STT": "56",
            "Số hóa đơn": "14",
            "Ngày tháng, năm phát hành": "24/12/2019",
            "Tháng, năm kê khai": "Q4/2019",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-12",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "1.065.601.969",
            "Thuế GTGT": "106.560.197",
            "Tổng tiền": "1.172.162.166"
        },
        {
            "STT": "",
            "Số hóa đơn": "",
            "Ngày tháng, năm phát hành": "",
            "Tháng, năm kê khai": "",
            "Tên người mua": "",
            "Mã số thuế người mua": "",
            "Mặt hàng": "Cộng",
            "Doanh số bán chưa có thuế": "13.586.921.052",
            "Thuế GTGT": "1.358.692.105",
            "Tổng tiền": "14.945.613.157"
        },
        {
            "STT": "1",
            "Số hóa đơn": "15",
            "Ngày tháng, năm phát hành": "14/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng cáp thuê bao tại dự án KDC",
            "Doanh số bán chưa có thuế": "26.870.994",
            "Thuế GTGT": "2.687.099",
            "Tổng tiền": "29.558.093"
        },
        {
            "STT": "2",
            "Số hóa đơn": "16",
            "Ngày tháng, năm phát hành": "15/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC các tuyến cáp quang phục vụ di dời",
            "Doanh số bán chưa có thuế": "104.097.993",
            "Thuế GTGT": "10.409.799",
            "Tổng tiền": "114.507.792"
        },
        {
            "STT": "3",
            "Số hóa đơn": "17",
            "Ngày tháng, năm phát hành": "16/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC các tuyến cáp quang phục vụ di dời",
            "Doanh số bán chưa có thuế": "94.251.886",
            "Thuế GTGT": "9.425.189",
            "Tổng tiền": "103.677.075"
        },
        {
            "STT": "4",
            "Số hóa đơn": "18",
            "Ngày tháng, năm phát hành": "16/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "600.711.721",
            "Thuế GTGT": "60.071.172",
            "Tổng tiền": "660.782.893"
        },
        {
            "STT": "5",
            "Số hóa đơn": "19",
            "Ngày tháng, năm phát hành": "16/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "806.223.702",
            "Thuế GTGT": "80.622.370",
            "Tổng tiền": "886.846.072"
        },
        {
            "STT": "6",
            "Số hóa đơn": "20",
            "Ngày tháng, năm phát hành": "17/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC các tuyến cáp quang phục vụ di dời",
            "Doanh số bán chưa có thuế": "95.149.948",
            "Thuế GTGT": "9.514.995",
            "Tổng tiền": "104.664.943"
        },
        {
            "STT": "7",
            "Số hóa đơn": "21",
            "Ngày tháng, năm phát hành": "17/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC các tuyến cáp quang phục vụ di dời",
            "Doanh số bán chưa có thuế": "78.659.073",
            "Thuế GTGT": "7.865.907",
            "Tổng tiền": "86.524.980"
        },
        {
            "STT": "8",
            "Số hóa đơn": "22",
            "Ngày tháng, năm phát hành": "17/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC các tuyến cáp phục vụ di dời",
            "Doanh số bán chưa có thuế": "240.247.623",
            "Thuế GTGT": "24.024.762",
            "Tổng tiền": "264.272.385"
        },
        {
            "STT": "9",
            "Số hóa đơn": "23",
            "Ngày tháng, năm phát hành": "17/1/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC các tuyến cáp phục vụ di dời",
            "Doanh số bán chưa có thuế": "109.941.514",
            "Thuế GTGT": "10.994.151",
            "Tổng tiền": "120.935.665"
        },
        {
            "STT": "10",
            "Số hóa đơn": "24",
            "Ngày tháng, năm phát hành": "24/01/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Công ty TNHH Diệp Song Minh",
            "Mã số thuế người mua": "310745965",
            "Mặt hàng": "TC các tuyến cáp quang phục vụ di dời",
            "Doanh số bán chưa có thuế": "89.486.407",
            "Thuế GTGT": "8.948.641",
            "Tổng tiền": "98.435.048"
        },
        {
            "STT": "11",
            "Số hóa đơn": "25",
            "Ngày tháng, năm phát hành": "25/2/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "109.442.205",
            "Thuế GTGT": "10.944.221",
            "Tổng tiền": "120.386.426"
        },
        {
            "STT": "12",
            "Số hóa đơn": "26",
            "Ngày tháng, năm phát hành": "25/3/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "845.583.621",
            "Thuế GTGT": "84.558.362",
            "Tổng tiền": "930.141.983"
        },
        {
            "STT": "13",
            "Số hóa đơn": "27",
            "Ngày tháng, năm phát hành": "26/3/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC tuyến cáp quang trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "251.958.840",
            "Thuế GTGT": "25.195.884",
            "Tổng tiền": "277.154.724"
        },
        {
            "STT": "14",
            "Số hóa đơn": "28",
            "Ngày tháng, năm phát hành": "27/3/2020",
            "Tháng, năm kê khai": "Q1/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "634.032.686",
            "Thuế GTGT": "63.403.269",
            "Tổng tiền": "697.435.955"
        },
        {
            "STT": "15",
            "Số hóa đơn": "30",
            "Ngày tháng, năm phát hành": "23/4/2020",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "125.201.232",
            "Thuế GTGT": "12.520.123",
            "Tổng tiền": "137.721.355"
        },
        {
            "STT": "16",
            "Số hóa đơn": "31",
            "Ngày tháng, năm phát hành": "12/5/20",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "243.139.533",
            "Thuế GTGT": "24.313.953",
            "Tổng tiền": "267.453.486"
        },
        {
            "STT": "17",
            "Số hóa đơn": "33",
            "Ngày tháng, năm phát hành": "25/5/2020",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "547.216.075",
            "Thuế GTGT": "54.721.607",
            "Tổng tiền": "601.937.682"
        },
        {
            "STT": "18",
            "Số hóa đơn": "35",
            "Ngày tháng, năm phát hành": "28/5/2020",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Thi công tuyến cáp phục vụ di dời ",
            "Doanh số bán chưa có thuế": "230.128.821",
            "Thuế GTGT": "23.012.882",
            "Tổng tiền": "253.141.703"
        },
        {
            "STT": "19",
            "Số hóa đơn": "36",
            "Ngày tháng, năm phát hành": "29/05/2020",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Thi công xây dựng tuyến cáp thuê bao",
            "Doanh số bán chưa có thuế": "68.766.612",
            "Thuế GTGT": "6.876.661",
            "Tổng tiền": "75.643.273"
        },
        {
            "STT": "20",
            "Số hóa đơn": "38",
            "Ngày tháng, năm phát hành": "29/5/2020",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC mở rộng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "179.144.004",
            "Thuế GTGT": "17.914.400",
            "Tổng tiền": "197.058.404"
        },
        {
            "STT": "21",
            "Số hóa đơn": "39",
            "Ngày tháng, năm phát hành": "11/6/20",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "488.807.249",
            "Thuế GTGT": "48.880.725",
            "Tổng tiền": "537.687.974"
        },
        {
            "STT": "22",
            "Số hóa đơn": "43",
            "Ngày tháng, năm phát hành": "20/7/2020",
            "Tháng, năm kê khai": "Q2/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "571.182.655",
            "Thuế GTGT": "57.118.265",
            "Tổng tiền": "628.300.920"
        },
        {
            "STT": "23",
            "Số hóa đơn": "44",
            "Ngày tháng, năm phát hành": "23/7/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "154.908.941",
            "Thuế GTGT": "15.490.894",
            "Tổng tiền": "170.399.835"
        },
        {
            "STT": "24",
            "Số hóa đơn": "45",
            "Ngày tháng, năm phát hành": "30/7/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng cáp thuê bao ",
            "Doanh số bán chưa có thuế": "138.303.286",
            "Thuế GTGT": "13.830.329",
            "Tổng tiền": "152.133.615"
        },
        {
            "STT": "25",
            "Số hóa đơn": "46",
            "Ngày tháng, năm phát hành": "30/7/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "446.067.667",
            "Thuế GTGT": "44.606.767",
            "Tổng tiền": "490.674.434"
        },
        {
            "STT": "26",
            "Số hóa đơn": "47",
            "Ngày tháng, năm phát hành": "5/8/20",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "414.056.668",
            "Thuế GTGT": "41.405.667",
            "Tổng tiền": "455.462.335"
        },
        {
            "STT": "27",
            "Số hóa đơn": "48",
            "Ngày tháng, năm phát hành": "25/8/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "204.344.325",
            "Thuế GTGT": "20.434.432",
            "Tổng tiền": "224.778.757"
        },
        {
            "STT": "28",
            "Số hóa đơn": "50",
            "Ngày tháng, năm phát hành": "31/8/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Lắp đặt bộ chia phục vụ nâng cấp mở rộng dung lượng mạng truy nhập",
            "Doanh số bán chưa có thuế": "131.658.149",
            "Thuế GTGT": "13.165.815",
            "Tổng tiền": "144.823.964"
        },
        {
            "STT": "29",
            "Số hóa đơn": "51",
            "Ngày tháng, năm phát hành": "11/9/20",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "617.683.625",
            "Thuế GTGT": "61.768.362",
            "Tổng tiền": "679.451.987"
        },
        {
            "STT": "30",
            "Số hóa đơn": "52",
            "Ngày tháng, năm phát hành": "11/9/20",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "169.001.115",
            "Thuế GTGT": "16.900.111",
            "Tổng tiền": "185.901.226"
        },
        {
            "STT": "31",
            "Số hóa đơn": "53",
            "Ngày tháng, năm phát hành": "14/9/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Lắp đặt bộ chia phục vụ nâng cấp mở rộng dung lượng mạng truy nhập CĐBR",
            "Doanh số bán chưa có thuế": "73.128.948",
            "Thuế GTGT": "7.312.895",
            "Tổng tiền": "80.441.843"
        },
        {
            "STT": "32",
            "Số hóa đơn": "54",
            "Ngày tháng, năm phát hành": "25/9/2020",
            "Tháng, năm kê khai": "Q3/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "390.284.376",
            "Thuế GTGT": "39.028.437",
            "Tổng tiền": "429.312.813"
        },
        {
            "STT": "33",
            "Số hóa đơn": "55",
            "Ngày tháng, năm phát hành": "8/10/20",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Lắp đặt bộ chia phục vụ nâng cấp mở rộng dung lượng mạng truy nhập",
            "Doanh số bán chưa có thuế": "170.029.627",
            "Thuế GTGT": "17.002.963",
            "Tổng tiền": "187.032.590"
        },
        {
            "STT": "34",
            "Số hóa đơn": "56",
            "Ngày tháng, năm phát hành": "21/10/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "443.991.461",
            "Thuế GTGT": "44.399.146",
            "Tổng tiền": "488.390.607"
        },
        {
            "STT": "35",
            "Số hóa đơn": "57",
            "Ngày tháng, năm phát hành": "28/10/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Lắp đặt bộ chia phục vụ nâng cấp mở rộng dung lượng mạng truy nhập",
            "Doanh số bán chưa có thuế": "164.710.938",
            "Thuế GTGT": "16.471.094",
            "Tổng tiền": "181.182.032"
        },
        {
            "STT": "36",
            "Số hóa đơn": "58",
            "Ngày tháng, năm phát hành": "28/10/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Mở rộng hạ tầng truy nhập mạng CĐBR tại Tiền Giang",
            "Doanh số bán chưa có thuế": "1.614.872.731",
            "Thuế GTGT": "161.487.273",
            "Tổng tiền": "1.776.360.004"
        },
        {
            "STT": "37",
            "Số hóa đơn": "59",
            "Ngày tháng, năm phát hành": "30/10/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "146.007.411",
            "Thuế GTGT": "14.600.741",
            "Tổng tiền": "160.608.152"
        },
        {
            "STT": "38",
            "Số hóa đơn": "60",
            "Ngày tháng, năm phát hành": "9/11/20",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Triển khai ngầm hóa, di dời mạng cáp viễn thông CĐBR tại TP.HCM",
            "Doanh số bán chưa có thuế": "217.459.108",
            "Thuế GTGT": "21.745.911",
            "Tổng tiền": "239.205.019"
        },
        {
            "STT": "39",
            "Số hóa đơn": "61",
            "Ngày tháng, năm phát hành": "16/11/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Cải tạo, sửa chữa cống bể ",
            "Doanh số bán chưa có thuế": "132.087.367",
            "Thuế GTGT": "13.208.737",
            "Tổng tiền": "145.296.104"
        },
        {
            "STT": "40",
            "Số hóa đơn": "62",
            "Ngày tháng, năm phát hành": "25/11/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Triển khai ngầm hóa, di dời mạng cáp viễn thông CĐBR tại TP.HCM",
            "Doanh số bán chưa có thuế": "152.884.311",
            "Thuế GTGT": "15.288.431",
            "Tổng tiền": "168.172.742"
        },
        {
            "STT": "41",
            "Số hóa đơn": "63",
            "Ngày tháng, năm phát hành": "25/11/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "XD các tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố",
            "Doanh số bán chưa có thuế": "115.037.435",
            "Thuế GTGT": "11.503.744",
            "Tổng tiền": "126.541.179"
        },
        {
            "STT": "42",
            "Số hóa đơn": "64",
            "Ngày tháng, năm phát hành": "30/11/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "TC cải tạo sửa chữa cống bể dự án ",
            "Doanh số bán chưa có thuế": "485.658.162",
            "Thuế GTGT": "48.565.816",
            "Tổng tiền": "534.223.978"
        },
        {
            "STT": "43",
            "Số hóa đơn": "65",
            "Ngày tháng, năm phát hành": "29/12/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "XD mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "375.805.264",
            "Thuế GTGT": "37.580.526",
            "Tổng tiền": "413.385.790"
        },
        {
            "STT": "44",
            "Số hóa đơn": "66",
            "Ngày tháng, năm phát hành": "29/12/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng cáp thuê bao",
            "Doanh số bán chưa có thuế": "222.269.165",
            "Thuế GTGT": "22.226.917",
            "Tổng tiền": "244.496.082"
        },
        {
            "STT": "45",
            "Số hóa đơn": "67",
            "Ngày tháng, năm phát hành": "29/12/2020",
            "Tháng, năm kê khai": "Q4/20",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "168.646.251",
            "Thuế GTGT": "16.864.625",
            "Tổng tiền": "185.510.876"
        },
        {
            "STT": "",
            "Số hóa đơn": "",
            "Ngày tháng, năm phát hành": "",
            "Tháng, năm kê khai": "",
            "Tên người mua": "",
            "Mã số thuế người mua": "",
            "Mặt hàng": "Cộng",
            "Doanh số bán chưa có thuế": "13.689.140.725",
            "Thuế GTGT": "1.368.914.070",
            "Tổng tiền": "15.058.054.795"
        },
        {
            "STT": "1",
            "Số hóa đơn": "68",
            "Ngày tháng, năm phát hành": "11/1/21",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng các tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố tại TP.HCM (Giai đoạn 2)",
            "Doanh số bán chưa có thuế": "78.874.489",
            "Thuế GTGT": "7.887.449",
            "Tổng tiền": "86.761.938"
        },
        {
            "STT": "2",
            "Số hóa đơn": "69",
            "Ngày tháng, năm phát hành": "14/1/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Mở rộng hạ tầng truy nhập mạng CĐBR tại Tiền Giang",
            "Doanh số bán chưa có thuế": "474.065.946",
            "Thuế GTGT": "47.406.595",
            "Tổng tiền": "521.472.541"
        },
        {
            "STT": "3",
            "Số hóa đơn": "70",
            "Ngày tháng, năm phát hành": "19/1/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy cập tại 56 trạm cố định băng rộng phục vụ ngầm hoá trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "352.823.559",
            "Thuế GTGT": "35.282.356",
            "Tổng tiền": "388.105.915"
        },
        {
            "STT": "4",
            "Số hóa đơn": "71",
            "Ngày tháng, năm phát hành": "20/1/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố tại TP.HCM (Giai đoạn 3)",
            "Doanh số bán chưa có thuế": "106.834.139",
            "Thuế GTGT": "10.683.414",
            "Tổng tiền": "117.517.553"
        },
        {
            "STT": "5",
            "Số hóa đơn": "72",
            "Ngày tháng, năm phát hành": "20/1/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "272.813.525",
            "Thuế GTGT": "27.281.352",
            "Tổng tiền": "300.094.877"
        },
        {
            "STT": "6",
            "Số hóa đơn": "73",
            "Ngày tháng, năm phát hành": "29/1/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng cáp thuê bao trạm CĐBR dự án CC Conic Garden; CC Parespring; CC Nguyễn Cửu Vân tại TP.HCM",
            "Doanh số bán chưa có thuế": "305.932.632",
            "Thuế GTGT": "30.593.263",
            "Tổng tiền": "336.525.895"
        },
        {
            "STT": "7",
            "Số hóa đơn": "74",
            "Ngày tháng, năm phát hành": "29/1/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng cáp thuê bao trạm CĐBR Tren địa bàn dự án CC Kim Hồng; CC 584 Tân Kiên; CC91 Phạm Văn Hai, TP.HCM",
            "Doanh số bán chưa có thuế": "20.989.064",
            "Thuế GTGT": "2.098.906",
            "Tổng tiền": "23.087.970"
        },
        {
            "STT": "8",
            "Số hóa đơn": "75",
            "Ngày tháng, năm phát hành": "2/2/21",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Lắp bộ chia phục vụ nâng cấp mở rộng dung lượng mạng tại các trạm HCM (Giai đoạn 6)",
            "Doanh số bán chưa có thuế": "248.360.802",
            "Thuế GTGT": "24.836.080",
            "Tổng tiền": "273.196.882"
        },
        {
            "STT": "9",
            "Số hóa đơn": "76",
            "Ngày tháng, năm phát hành": "2/2/21",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR cho 4 công trình dự án toà nhà khu đô thị tại TP.HCM",
            "Doanh số bán chưa có thuế": "992.834.804",
            "Thuế GTGT": "99.283.480",
            "Tổng tiền": "1.092.118.284"
        },
        {
            "STT": "10",
            "Số hóa đơn": "78",
            "Ngày tháng, năm phát hành": "4/3/21",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng các tuyến truyền dẫn cáp quang phục vụ chương trình CRAN tại TP.HCM",
            "Doanh số bán chưa có thuế": "63.868.346",
            "Thuế GTGT": "6.386.835",
            "Tổng tiền": "70.255.181"
        },
        {
            "STT": "11",
            "Số hóa đơn": "80",
            "Ngày tháng, năm phát hành": "25/3/2021",
            "Tháng, năm kê khai": "Q1/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Xây dựng và mở mạng hạ tầng truy nhập mạng CĐBR tại TP.HCM",
            "Doanh số bán chưa có thuế": "2.944.491",
            "Thuế GTGT": "294.449",
            "Tổng tiền": "3.238.940"
        },
        {
            "STT": "12",
            "Số hóa đơn": "81",
            "Ngày tháng, năm phát hành": "9/4/21",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Công ty TNHH Diệp Song Minh",
            "Mã số thuế người mua": "310745965",
            "Mặt hàng": "Triển khai ngầm hoá, di dời mạng cáp viễn thông CĐBR tại TP.HCM (Giai đoạn 3)",
            "Doanh số bán chưa có thuế": "419.516.424",
            "Thuế GTGT": "41.951.642",
            "Tổng tiền": "461.468.066"
        },
        {
            "STT": "13",
            "Số hóa đơn": "82",
            "Ngày tháng, năm phát hành": "21/4/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố tại TP.HCM (Giai đoạn 4)",
            "Doanh số bán chưa có thuế": "55.130.336",
            "Thuế GTGT": "5.513.034",
            "Tổng tiền": "60.643.370"
        },
        {
            "STT": "14",
            "Số hóa đơn": "83",
            "Ngày tháng, năm phát hành": "26/4/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Mở rộng hạ tầng truy nhập mạng CĐBR tại TP.HCM",
            "Doanh số bán chưa có thuế": "282.893.715",
            "Thuế GTGT": "28.289.372",
            "Tổng tiền": "311.183.087"
        },
        {
            "STT": "15",
            "Số hóa đơn": "84",
            "Ngày tháng, năm phát hành": "29/4/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Mở rộng hạ tầng truy nhập mạng CĐBR tại Đồng Nai",
            "Doanh số bán chưa có thuế": "938.918.364",
            "Thuế GTGT": "93.891.836",
            "Tổng tiền": "1.032.810.200"
        },
        {
            "STT": "16",
            "Số hóa đơn": "85",
            "Ngày tháng, năm phát hành": "19/5/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR tại TP.HCM (Giai đoạn 16)",
            "Doanh số bán chưa có thuế": "338.039.518",
            "Thuế GTGT": "33.803.952",
            "Tổng tiền": "371.843.470"
        },
        {
            "STT": "17",
            "Số hóa đơn": "87",
            "Ngày tháng, năm phát hành": "8/6/21",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Tổng công ty mạng lưới Viettel-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Mở rộng hạ tầng truy nhập mạng CĐBR tại TP.HCM (Giai đoạn 9)",
            "Doanh số bán chưa có thuế": "186.568.801",
            "Thuế GTGT": "18.656.880",
            "Tổng tiền": "205.225.681"
        },
        {
            "STT": "18",
            "Số hóa đơn": "88",
            "Ngày tháng, năm phát hành": "14/6/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Triển khai ngầm hoá, di dời mạng cáp viễn thông CĐBR tại TP.HCM (Giai đoạn 4)",
            "Doanh số bán chưa có thuế": "121.873.733",
            "Thuế GTGT": "12.187.373",
            "Tổng tiền": "134.061.106"
        },
        {
            "STT": "19",
            "Số hóa đơn": "89",
            "Ngày tháng, năm phát hành": "21/6/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Thi công cải tạo cống bể KDC Hiệp Thành City, KDC Huy Hoàng GDD, KDC Thế Minh tại TP.HCM",
            "Doanh số bán chưa có thuế": "1.778.889.356",
            "Thuế GTGT": "177.888.936",
            "Tổng tiền": "1.956.778.292"
        },
        {
            "STT": "20",
            "Số hóa đơn": "90",
            "Ngày tháng, năm phát hành": "25/6/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng các tuyến truyền dẫn cascp quang phục vụ kiên cố, củng cố tại HCM",
            "Doanh số bán chưa có thuế": "6.340.557",
            "Thuế GTGT": "634.056",
            "Tổng tiền": "6.974.613"
        },
        {
            "STT": "21",
            "Số hóa đơn": "91",
            "Ngày tháng, năm phát hành": "25/6/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR tại TP.HCM (Giai đoạn 17)",
            "Doanh số bán chưa có thuế": "92.704.389",
            "Thuế GTGT": "9.270.439",
            "Tổng tiền": "101.974.828"
        },
        {
            "STT": "22",
            "Số hóa đơn": "92",
            "Ngày tháng, năm phát hành": "28/6/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Sửa chữa, cải tạo tuyến cống bể ngầm tại KDC Huy Hoàng, Bình Chiểu, An Phú, An Khánh, Q.2 - Thủ Đức, TP.HCM",
            "Doanh số bán chưa có thuế": "532.257.548",
            "Thuế GTGT": "53.225.755",
            "Tổng tiền": "585.483.303"
        },
        {
            "STT": "23",
            "Số hóa đơn": "93",
            "Ngày tháng, năm phát hành": "28/6/2021",
            "Tháng, năm kê khai": "Q2/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Sửa chữa, cải tạo tuyến cống bể ngầm tại khu nhà đường Tăng Nhơn Phú, Q.9 & KDC Hai Thành - Q.Bình Tân, TP.HCM",
            "Doanh số bán chưa có thuế": "283.380.938",
            "Thuế GTGT": "28.338.094",
            "Tổng tiền": "311.719.032"
        },
        {
            "STT": "24",
            "Số hóa đơn": "94",
            "Ngày tháng, năm phát hành": "29/7/2021",
            "Tháng, năm kê khai": "Q3/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố tại TP.HCM",
            "Doanh số bán chưa có thuế": "86.635.623",
            "Thuế GTGT": "8.663.562",
            "Tổng tiền": "95.299.185"
        },
        {
            "STT": "25",
            "Số hóa đơn": "95",
            "Ngày tháng, năm phát hành": "24/8/2021",
            "Tháng, năm kê khai": "Q3/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng cáo thuê bao trạm CĐBR tại dự án CC ParkLand; CC Useful Apartment; CC Docklands, TP.HCM",
            "Doanh số bán chưa có thuế": "80.904.448",
            "Thuế GTGT": "8.090.445",
            "Tổng tiền": "88.994.893"
        },
        {
            "STT": "26",
            "Số hóa đơn": "96",
            "Ngày tháng, năm phát hành": "25/8/2021",
            "Tháng, năm kê khai": "Q3/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Triển khai ngầm hoá, di dời mạng cáp viễn thông CĐBR tại TP.HCM (Giai đoạn 5)",
            "Doanh số bán chưa có thuế": "170.130.637",
            "Thuế GTGT": "17.013.064",
            "Tổng tiền": "187.143.701"
        },
        {
            "STT": "27",
            "Số hóa đơn": "98",
            "Ngày tháng, năm phát hành": "25/8/2021",
            "Tháng, năm kê khai": "Q3/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập mạng tại trạm CĐBR trên địa bàn dự án KDC Đông Nam GDD; Vạn Phúc City -Thủ Đức, TP.HCM",
            "Doanh số bán chưa có thuế": "79.101.456",
            "Thuế GTGT": "7.910.146",
            "Tổng tiền": "87.011.602"
        },
        {
            "STT": "28",
            "Số hóa đơn": "99",
            "Ngày tháng, năm phát hành": "1/9/21",
            "Tháng, năm kê khai": "Q3/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR tại TP.HCM (GĐ 18)",
            "Doanh số bán chưa có thuế": "205.836.171",
            "Thuế GTGT": "20.583.617",
            "Tổng tiền": "226.419.788"
        },
        {
            "STT": "29",
            "Số hóa đơn": "100",
            "Ngày tháng, năm phát hành": "20/9/2021",
            "Tháng, năm kê khai": "Q3/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng các tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố tại TP.HCM (Giai đoạn 7)",
            "Doanh số bán chưa có thuế": "59.858.288",
            "Thuế GTGT": "5.985.829",
            "Tổng tiền": "65.844.117"
        },
        {
            "STT": "30",
            "Số hóa đơn": "101",
            "Ngày tháng, năm phát hành": "9/10/21",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Nâng cấp, sửa chữa tuyến cáp phục vụ củng cố tuyến cáp trục 1B trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "60.545.486",
            "Thuế GTGT": "6.054.549",
            "Tổng tiền": "660.600.035"
        },
        {
            "STT": "31",
            "Số hóa đơn": "102",
            "Ngày tháng, năm phát hành": "3/11/21",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Xây dựng tuyến cáp truyền dẫn cáp quang phục vụ kiên cố, củng cố tại HCM",
            "Doanh số bán chưa có thuế": "37.976.894",
            "Thuế GTGT": "3.797.689",
            "Tổng tiền": "41.774.583"
        },
        {
            "STT": "32",
            "Số hóa đơn": "103",
            "Ngày tháng, năm phát hành": "5/11/21",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Sửa chữa, cải tạo tuyến cống bể KDC Ninh Giang; KDC Phong Phú 4; KDC Conic Skyway; KDC Khang Điền; KDC Cát Lái -TP.HCM",
            "Doanh số bán chưa có thuế": "173.150.028",
            "Thuế GTGT": "17.315.003",
            "Tổng tiền": "190.465.031"
        },
        {
            "STT": "33",
            "Số hóa đơn": "104",
            "Ngày tháng, năm phát hành": "5/11/21",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng truy nhập CĐBR tại TP.HCM (GĐ 19)",
            "Doanh số bán chưa có thuế": "46.437.472",
            "Thuế GTGT": "4.643.747",
            "Tổng tiền": "51.081.219"
        },
        {
            "STT": "34",
            "Số hóa đơn": "105",
            "Ngày tháng, năm phát hành": "25/11/2021",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Triển khai ngầm hoá, di dời mạng cáp viễn thông CĐBR tại TP.HCM (GĐ 6)",
            "Doanh số bán chưa có thuế": "563.866.066",
            "Thuế GTGT": "56.386.607",
            "Tổng tiền": "620.252.673"
        },
        {
            "STT": "35",
            "Số hóa đơn": "106",
            "Ngày tháng, năm phát hành": "30/11/2021",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Cải tạo, nâng cao độ bể 4TG tại 28 Đoàn Như Hài & giao lộ Nguyễn Huệ -TP.HCM",
            "Doanh số bán chưa có thuế": "9.076.147",
            "Thuế GTGT": "907.615",
            "Tổng tiền": "9.983.762"
        },
        {
            "STT": "36",
            "Số hóa đơn": "107",
            "Ngày tháng, năm phát hành": "30/11/2021",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Thu hồi tuyến cáp quang ADSS 220KV Hóc Môn trên địa bàn TP.HCM",
            "Doanh số bán chưa có thuế": "32.968.817",
            "Thuế GTGT": "3.296.882",
            "Tổng tiền": "36.265.699"
        },
        {
            "STT": "37",
            "Số hóa đơn": "1",
            "Ngày tháng, năm phát hành": "23/12/2021",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": " Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Xây dựng các tuyến truyền dẫn cáp quang phục vụ kiên cố, củng cố tại HCM",
            "Doanh số bán chưa có thuế": "177.462.945",
            "Thuế GTGT": "17.746.294",
            "Tổng tiền": "195.209.239"
        },
        {
            "STT": "38",
            "Số hóa đơn": "2",
            "Ngày tháng, năm phát hành": "23/12/2021",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-012",
            "Mặt hàng": "Thu hồi và huỷ tuyến cáp quang ADSS trên đường dây 220KV Hóc Môn - Thuận An (trên địa phận Bình Dương)",
            "Doanh số bán chưa có thuế": "21.205.138",
            "Thuế GTGT": "2.120.514",
            "Tổng tiền": "23.325.652"
        },
        {
            "STT": "39",
            "Số hóa đơn": "3",
            "Ngày tháng, năm phát hành": "28/12/2021",
            "Tháng, năm kê khai": "Q4/21",
            "Tên người mua": "Viettel TP.HCM-CN Tập Đoàn Viễn Thông Quân Đội",
            "Mã số thuế người mua": "0100109106-122",
            "Mặt hàng": "Xây dựng mạng cáp thuê bao tại trạm CĐBR trên địa bàn dự án Vinhomes Grand Park_Khu thấp tầng; KDC City Land - TP.HCM",
            "Doanh số bán chưa có thuế": "404.213.608",
            "Thuế GTGT": "40.421.361",
            "Tổng tiền": "444.634.969"
        },
        {
            "STT": "",
            "Số hóa đơn": "",
            "Ngày tháng, năm phát hành": "",
            "Tháng, năm kê khai": "",
            "Tên người mua": "",
            "Mã số thuế người mua": "",
            "Mặt hàng": "Cộng",
            "Doanh số bán chưa có thuế": "10.166.224.700",
            "Thuế GTGT": "1.016.622.472",
            "Tổng tiền": "11.776.847.172"
        }
    ]